version: "3"
services:
  db:
    image: postgres:latest
    container_name: faq-postgres
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=faq-db
      - POSTGRES_USER=faq
      - POSTGRES_PASSWORD=rise2Shine!

  rabbitmq:
    image: rabbitmq:latest
    container_name: faq-rabbitmq
    networks:
      - default
    ports:
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_data:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest!

  publish-api:
    image: uphop/faq-publish-api
    container_name: faq-publish-api
    networks:
      - default
    ports:
      - 5000:5000
    build: 
      context: ./faq-publish-api
      dockerfile: publish-api.Dockerfile
    depends_on: 
      - db

  publish-broker:
    image: uphop/faq-publish-broker
    container_name: faq-publish-broker
    networks:
      - default
    volumes: 
      # https://github.com/docker/for-mac/issues/4755
      - /var/run/docker.sock.raw:/var/run/docker.sock
    build: 
      context: ./faq-publish-api
      dockerfile: publish-broker.Dockerfile
    depends_on: 
      - rabbitmq

  capture-actions:
    image: uphop/faq-capture-actions
    container_name: faq-capture-actions
    networks:
      - default
    ports:
      - 5055:5055
    build: 
      context: ./faq-capture-bot
      dockerfile: capture-actions.Dockerfile
  
  capture-bot:
    image: uphop/faq-capture-bot
    container_name: faq-capture-bot
    networks:
      - default
    ports:
      - 5005:5005
    build: 
      context: ./faq-capture-bot
      dockerfile: capture-bot.Dockerfile
    depends_on: 
      - db

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  default:
    driver: bridge
